spring.application.name=marketingtoolshub
 
server.port=8080

gemini.api.key=AIzaSyAW37NasX88WqmVza9AHKooiVZS0VM-9KQ
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent