spring.application.name=marketingtoolshub
 
server.port=8080

gemini.api.key=AIzaSyBeN9a0LmAKEvCi8mSX4G2YHEYAdD2FDcs
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent