spring.application.name=marketingtoolshub
 
server.port=8080

gemini.api.key=AIzaSyBAq3MBtuzUcy5t2vW5ahuYh7WMbxVoJIY
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent